version: "3.9"
services:
    redisdb:
        image: redis
        container_name: redisdb
        ports:
            - 6379:6379
        volumes:
            - db-data:/data/db
        environment:
            - REDIS_REPLICATION_MODE=master
volumes:
  db-data:
    driver: local
